#ifndef __ONLINE_GAME_GS_COOLDOWN_CONFIG_H__
#define __ONLINE_GAME_GS_COOLDOWN_CONFIG_H__

//��λΪ����
#define EMOTE_COOLDOWN_TIME		4000
#define FASHION_COOLDOWN_TIME		1000
#define DROPMONEY_COOLDOWN_TIME		1671
#define DROPITEM_COOLDOWN_TIME  	321	
#define FACEPILL_COOLDOWN_TIME  	300000
#define FACETICKET_COOLDOWN_TIME 	60*1000		//1Сʱ��ȴ
#define RECURRECT_SCROLL_COOLDOWN_TIME	300000
//#define SOUL_STONE_COOLDOWN_TIME	1800000			//��Сʱ��ȴʱ��
#define SOUL_STONE_COOLDOWN_TIME	18000			//��Сʱ��ȴʱ��
#define RUSH_FLAY_COOLDOWN_TIME		20000			//���г����ȴʱ��
#define TOWN_SCROLL_COOLDOWN_TIME	5000			//�سǷ���ȴʱ��
#define ITEM_MOBGEN_COOLDOWN_TIME	3000			//��Ʒ����������ȴʱ��
#define QUERY_OTHER_EQUIP_COOLDOWN_TIME	20000			//�쿴����װ������ȴʱ��
#define PET_FOOD_COOLDOWN_TIME		60000			//ι���������ȴʱ��
#define FIREWORKS_COOLDOWN_TIME		1000			//ʹ�ñ�׼�̻���ʱ��
#define SKILLTRIGGER_COOLDOWN_TIME	120000			//ʹ�ü�����Ʒ����ȴʱ��
#define REFINE_COOLDOWN_TIME		1000			//�����Ͱ���ص���ȴʱ��
#define DYE_COOLDOWN_TIME		1000			//Ⱦɫ�� ��ȴʱ�� 
#define CAST_ELF_SKILL_COOLDOWN_TIME		1000		//ʩ��С���鼼�ܵĹ�����ȴ lgc
#define ELF_CMD_COOLDOWN_TIME	1000			//����С����ı䰲ȫ״̬��ע�뾭��
#define GET_MALL_PRICE_COOLDOWN_TIME	30000	
#define QUERY_OTHER_PROPERTY_COOLDOWN_TIME	5000	//�쿴�������Ե���ȴʱ��
#define SKILLTRIGGER2_COOLDOWN_TIME			1000	//ʹ�ü�����Ʒ2����ȴʱ��
#define EQUIP_FASHION_ITEM_COOLDOWN_TIME	55000	//ʱװ��װ��ȴʱ��
#define GET_DIVIDEND_MALL_PRICE_COOLDOWN_TIME	30000	
#define	MULTI_EXCHANGE_ITEM_COOLDOWN_TIME		10000	//�����ֿ�/������ȴ
#define TEAM_CONGREGATE_COOLDOWN_TIME			180000	//���鼯�����ʹ����ȴʱ��
#define FACTION_CONGREGATE_COOLDOWN_TIME		180000	//���ɼ������ʹ����ȴʱ��
#define FACTION_ALLIANCE_CONGREGATE_COOLDOWN_TIME		300000	//���ɼ������ʹ����ȴʱ��
#define DPS_DPH_RANK_COOLDOWN_TIME				1000	//��ȡDPS���а���ȴʱ��
#define PLAYER_JOIN_FORCE_COOLDOWN_TIME			24*3600*1000
#define PLAYER_LEAVE_FORCE_COOLDOWN_TIME		7*24*3600*1000
#define TOGGLE_ONLINE_AWARD_COOLDOWN_TIME		1000
#define COUNTRY_JOIN_APPLY_COOLDOWN_TIME		30000
#define COUNTRY_CHAT_COOLDOWN_TIME 				3000
#define CHANGEDS_COOLDOWN_TIME 					30000
#define TOUCH_QUERY_COOLDOWN_TIME 				1000
#define SWITCH_IN_PARALLEL_WORLD_COOLDOWN_TIME	3000
#define QUERY_PARALLEL_WORLD_COOLDOWN_TIME		3000
#define GIFTCARD_REDEEM_COOLDOWN_TIME 				1000
#define TRICKBATTLE_APPLY_COOLDOWN_TIME			30000
#define AUTOTEAM_SET_GOAL_COOLDOWN_TIME 		5000
#define PLAYER_GATHER_COOLDOWN_TIME				500		//��Ҳɼ�����ȴʱ�䣬��ֹ����ظ����
#define COUNTRYBATTLE_LIVESHOW_COOLDOWN_TIME 	4000
#define PLAYER_QUERY_MAFIA_PVP_COOLDOWN_TIME	5000
#define SOLO_CHALLENGE_ENTER_COOLDOWN_TIME      15000
#define SOLO_CHALLENGE_RANK_COOLDOWN_TIME       1000    // ��һ�ȡ���˸������а����ȴʱ�� (ms)
#define MNFACTION_JOIN_APPLY_COOLDOWN_TIME		30000
#define MNFACTION_RANK_COOLDOWN_TIME		30000
#define MNFACTION_GET_DOMAIN_DATA_COOLDOWN_TIME		10000
#define GLOABL_CRY_COOLDOWN_TIME				2000
#define GET_CASH_VIP_MALL_PRICE_COOLDOWN_TIME   30000
#define FIX_POSITION_TRANSMIT_COOLDOWN_TIME	    60000
#define LOOKUP_ENEMY_COOLDOWN_TIME              60000     // 60s
#define RESURRECT_BY_CASH_COOLDOWN_TIME         (15 * 60 * 1000)    // 15min
#define REFINE_BIBLE_COOLDOWN_TIME				1000			//�����Ͱ���ص���ȴʱ��
#define CARRIER_COOLDOWN_TIME					1000
#define RUNE_ESSENCE_COOLDOWN_TIME				1000
#define ARENA_OF_AURORA_RANK_COOLDOWN_TIME      3000
#define ARENA_OF_AURORA_SEARCH_COOLDOWN_TIME    8000
#define IDX_TIME_COOLDOWN		1800000

enum 
{
	COOLDOWN_INDEX_NULL,
	COOLDOWN_INDEX_PVP,		//û�ã���ռλ
	COOLDOWN_INDEX_EMOTE,
	COOLDOWN_INDEX_REJUVENATION_POTION,
	COOLDOWN_INDEX_SWITCH_FASHION,
	COOLDOWN_INDEX_DROP_MONEY,
	COOLDOWN_INDEX_DROP_ITEM,
	COOLDOWN_INDEX_FACEPILL,
	COOLDOWN_INDEX_FACETICKET,
	COOLDOWN_INDEX_RECURRECT_SCROLL,
	COOLDOWN_INDEX_SOUL_STONE,
	COOLDOWN_INDEX_HP_POTION,
	COOLDOWN_INDEX_MP_POTION,
	COOLDOWN_INDEX_ANITDOTE_POTION,
	COOLDOWN_INDEX_RUSH_FLY,
	COOLDOWN_INDEX_TOWN_SCROLL,
	COOLDOWN_INDEX_MOV_GEN,
	COOLDOWN_INDEX_QUERY_OTHER_EQUIP,
	COOLDOWN_INDEX_FEED_PET,
	COOLDOWN_INDEX_FIREWORKS,
	COOLDOWN_INDEX_FARCRY,
	COOLDOWN_INDEX_SKILL_TRIGGER,
	COOLDOWN_INDEX_REFINE,
	COOLDOWN_INDEX_DEF_RUNE,
	COOLDOWN_INDEX_AUTO_HP,
	COOLDOWN_INDEX_AUTO_MP,
	COOLDOWN_INDEX_DBL_EXP,
	COOLDOWN_INDEX_DYE,
	COOLDOWN_INDEX_TEAM_RELATION,
	COOLDOWN_INDEX_REFINE_TRANSMIT,
	COOLDOWN_INDEX_CAST_ELF_SKILL,	//lgc
	COOLDOWN_INDEX_ELF_CMD,
	COOLDOWM_INDEX_GET_MALL_PRICE,
	COOLDOWN_INDEX_QUERY_OTHER_PROPERTY,
	COOLDOWN_INDEX_SKILLTRIGGER2,
	COOLDOWN_INDEX_SKILLCOMMONCOOLDOWN0,
	COOLDOWN_INDEX_SKILLCOMMONCOOLDOWN1,
	COOLDOWN_INDEX_SKILLCOMMONCOOLDOWN2,
	COOLDOWN_INDEX_SKILLCOMMONCOOLDOWN3,
	COOLDOWN_INDEX_SKILLCOMMONCOOLDOWN4,
	COOLDOWN_INDEX_RUNECOMMONCOOLDOWN0,
	COOLDOWN_INDEX_RUNECOMMONCOOLDOWN1,
	COOLDOWN_INDEX_RUNECOMMONCOOLDOWN2,
	COOLDOWN_INDEX_RUNECOMMONCOOLDOWN3,
	COOLDOWN_INDEX_RUNECOMMONCOOLDOWN4,
	COOLDOWN_INDEX_EQUIP_FASHION_ITEM,
	COOLDOWM_INDEX_GET_DIVIDEND_MALL_PRICE,
	COOLDOWN_INDEX_MULTI_EXCHANGE_ITEM,
	COOLDOWN_INDEX_TEAM_CONGREGATE,
	COOLDOWN_INDEX_FACTION_CONGREGATE,
	COOLDOWN_INDEX_DPS_DPH_RANK,
	COOLDOWN_INDEX_PLAYER_JOIN_FORCE,
	COOLDOWN_INDEX_PLAYER_LEAVE_FORCE,
	COOLDOWN_INDEX_TOGGLE_ONLINE_AWARD,
	COOLDOWN_INDEX_COUNTRY_JOIN_APPLY,
	COOLDOWN_INDEX_COUNTRY_CHAT,
	COOLDOWN_INDEX_CHANGEDS,
	COOLDOWN_INDEX_TOUCHTRADE,
	COOLDOWN_INDEX_SWITCH_IN_PARALLEL_WORLD,
	COOLDOWN_INDEX_QUERY_PARALLEL_WORLD,
	COOLDOWN_INDEX_GIFTCARD_REDEEM,
	COOLDOWM_INDEX_TRICKBATTLE_APPLY,
	COOLDOWM_INDEX_AUTOTEAM_SET_GOAL,
	COOLDOWN_INDEX_PLAYER_GATHER,
	COOLDOWN_INDEX_COUNTRYBATTLE_LIVESHOW,
	COOLDOWN_INDEX_QUERY_MAFIA_PVP_INFO,        // 65
    COOLDOWN_INDEX_ENTER_SOLO_CHALLENGE,
    COOLDOWN_INDEX_SOLO_CHALLENGE_RANK,
	COOLDOWN_INDEX_SOLO_CHALLENGE_BUFF_0,
	COOLDOWN_INDEX_SOLO_CHALLENGE_BUFF_1,
	COOLDOWN_INDEX_SOLO_CHALLENGE_BUFF_2,       // 70
	COOLDOWN_INDEX_SOLO_CHALLENGE_BUFF_3,
	COOLDOWN_INDEX_SOLO_CHALLENGE_BUFF_4,
	COOLDOWN_INDEX_SOLO_CHALLENGE_BUFF_5,
	COOLDOWN_INDEX_SOLO_CHALLENGE_BUFF_6,
	COOLDOWN_INDEX_SOLO_CHALLENGE_BUFF_7,       // 75
	COOLDOWN_INDEX_SOLO_CHALLENGE_BUFF_8,
	COOLDOWN_INDEX_SOLO_CHALLENGE_BUFF_9,
	COOLDOWN_INDEX_SOLO_CHALLENGE_BUFF_10,
	COOLDOWN_INDEX_SOLO_CHALLENGE_BUFF_11,
	COOLDOWN_INDEX_SOLO_CHALLENGE_BUFF_12,      // 80
	COOLDOWN_INDEX_SOLO_CHALLENGE_BUFF_13,
	COOLDOWN_INDEX_SOLO_CHALLENGE_BUFF_14,
	COOLDOWN_INDEX_SOLO_CHALLENGE_BUFF_15,
	COOLDOWN_INDEX_MNFACTION_JOIN_APPLY,
	COOLDOWN_INDEX_MNFACTION_RANK,              // 85
	COOLDOWN_INDEX_MNFACTION_GET_DOMAIN_DATA,
	COOLDOWN_INDEX_GLOBAL_CRY,
    COOLDOWM_INDEX_GET_CASH_VIP_MALL_PRICE,
	COOLDOWN_INDEX_FIX_POSITION_TRANSMIT,
    COOLDOWN_INDEX_LOOKUP_ENEMY,                // 90
    COOLDOWN_INDEX_RESURRECT_BY_CASH,

	//joslian
	COOLDOWN_INDEX_PLAYER_USE_AUTOSWAP,
	COOLDOWN_INDEX_FACTION_ALLIANCE_CONGREGATE,
	//joslian end

	COOLDOWN_INDEX_SOLO_CHALLENGE_BUFF_START = COOLDOWN_INDEX_SOLO_CHALLENGE_BUFF_0,        // 68
	COOLDOWN_INDEX_SOLO_CHALLENGE_BUFF_END   = COOLDOWN_INDEX_SOLO_CHALLENGE_BUFF_15,       // 83

	COOLDOWM_INDEX_ARENAOFAURORA_SEARCH = 105,
	COOLDOWM_INDEX_ARENAOFAURORA_RANKING = 108,

	COOLDOWN_INDEX_KID_TRANSFORMATION = 139,
	COOLDOWN_INDEX_CELESTIAL_MEMORIAL = 157,
	COOLDOWN_INDEX_COMMONCOOLDOWNSTART = COOLDOWN_INDEX_SKILLCOMMONCOOLDOWN0,

	COOLDOWN_INDEX_CHEATER = 1000,
	COOLDOWN_INDEX_ANTI_CHEAT = 1001,
	COOLDOWN_SKILL_START = 1024,

};

#endif

